name: jaynetwork
description: A network handler for flutter.
version: 2.0.0
homepage: https://github.com/jbankz/JayNetworkHelper.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  connectivity: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4

flutter:
